description: 'scsi: core: Fix error handling of scsi_host_alloc()'
references:
- https://www.cve.org/CVERecord?id=CVE-2021-47258
- https://git.kernel.org/stable/c/8958181c1663e24a13434448e7d6b96b5d04900a
- https://git.kernel.org/stable/c/db08ce595dd64ea9859f7d088b51cbfc8e685c66
- https://git.kernel.org/stable/c/2dc85045ae65b9302a1d2e2ddd7ce4c030153a6a
- https://git.kernel.org/stable/c/79296e292d67fa7b5fb8d8c27343683e823872c8
- https://git.kernel.org/stable/c/7a696ce1d5d16a33a6cd6400bbcc0339b2460e11
- https://git.kernel.org/stable/c/45d83db4728127944b237c0c8248987df9d478e7
- https://git.kernel.org/stable/c/66a834d092930cf41d809c0e989b13cd6f9ca006
- https://lore.kernel.org/linux-cve-announce/2024052146-CVE-2021-47258-f276@gregkh/
- https://git.kernel.org/linus/66a834d092930cf41d809c0e989b13cd6f9ca006
comments:
  cip/cip-kernel-sec: Introduced commit is not determined.Fixed in v5.13-rc6.
  cip/masami: "It seems as if Linux 4.4 need to call put_device in error path \ninstead\
    \ of calling kfree as well."
  debian/carnil: First introducing commit could not be determined.
fixed-by:
  cip/4.19: [2dc85045ae65b9302a1d2e2ddd7ce4c030153a6a]
  cip/4.19-rt: [2dc85045ae65b9302a1d2e2ddd7ce4c030153a6a]
  cip/5.10: [7a696ce1d5d16a33a6cd6400bbcc0339b2460e11]
  cip/5.10-rt: [7a696ce1d5d16a33a6cd6400bbcc0339b2460e11]
  debian/buster-security: ['version:debian/4.19.208-1']
  mainline: [66a834d092930cf41d809c0e989b13cd6f9ca006]
  stable/4.14: [db08ce595dd64ea9859f7d088b51cbfc8e685c66]
  stable/4.19: [2dc85045ae65b9302a1d2e2ddd7ce4c030153a6a]
  stable/4.9: [8958181c1663e24a13434448e7d6b96b5d04900a]
  stable/5.10: [7a696ce1d5d16a33a6cd6400bbcc0339b2460e11]
  stable/5.4: [79296e292d67fa7b5fb8d8c27343683e823872c8]
  ubuntu/bionic: [1798402415740d7d552fd8284c29e241ef6c975b]
  ubuntu/focal: [a967617d3f5b5da71848ca56d6dbd1b79938b9a0]
  ubuntu/groovy: [2b0d2da8e14e77289151a2f388f2b30572d9757a]
