description: A use-after-free bug was found in the io_uring
references:
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.10.y&id=08681391b84da27133deefaaddefd0acfa90c2be
- https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.10.y&id=da24142b1ef9fd5d36b76e36bab328a5b27523e8
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-1872
- https://ubuntu.com/security/notices/USN-6044-1
- https://ubuntu.com/security/notices/USN-6051-1
- https://ubuntu.com/security/notices/USN-6070-1
- https://ubuntu.com/security/notices/USN-6107-1
- https://ubuntu.com/security/notices/USN-6133-1
- https://ubuntu.com/security/notices/USN-6134-1
comments:
  debian/carnil: |-
    No single upstream patch exists for this issue, it was fixed as
    part of the file assignment changes that went into the 5.18
    cycle. Take 5106dd6e74ab ("io_uring: propagate issue_flags
    state down to file assignment") as the relevant commit for
    tracking in higher versions (in 5.18-rc2, 5.17.3).
  masami: "Kernel 5.4 does not contain vulnerable function io_file_get_fixed()\nso\
    \ it will not be affected. "
fixed-by:
  cip/5.10: [08681391b84da27133deefaaddefd0acfa90c2be, da24142b1ef9fd5d36b76e36bab328a5b27523e8]
  cip/5.10-rt: [08681391b84da27133deefaaddefd0acfa90c2be, da24142b1ef9fd5d36b76e36bab328a5b27523e8]
  mainline: [5106dd6e74ab6c94daac1c357094f11e6934b36f]
  stable/5.10: [08681391b84da27133deefaaddefd0acfa90c2be, da24142b1ef9fd5d36b76e36bab328a5b27523e8]
  ubuntu/focal: ['version:5.4.0-9.12']
ignore:
  cip/4.19: Not affected
  cip/4.19-rt: Not affected
  cip/4.4: Not affected
  cip/4.4-rt: Not affected
  cip/4.4-st: Not affected
  stable/4.14: Not affected
  stable/4.19: Not affected
  stable/5.4: Not affected
