description: |-
  A use after free issue was discovered in driver/firewire in
  outbound_phy_packet_callback in the Linux Kernel. In this flaw a local
  attacker with special privilege may cause a use after free problem when
  queue_event() fails.
references:
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-3159
- https://git/kernel.org/linus/b7c81f80246fac44077166f3e07103affe6db8ff
- https://github.com/torvalds/linux/commit/b7c81f80246fac44077166f3e07103affe6db8ff
- https://bugzilla.redhat.com/show_bug.cgi?id=2213414
- https://git.kernel.org/linus/b7c81f80246fac44077166f3e07103affe6db8ff
introduced-by:
  mainline: [850bb6f23b93c04ce1e4509a87fa607dc17d97c1]
fixed-by:
  cip/4.19: [34380b5647f13fecb458fea9a3eb3d8b3a454709]
  cip/4.19-rt: [34380b5647f13fecb458fea9a3eb3d8b3a454709]
  cip/4.4: [6f1117c4227fec8d321531df8cd72de9b6e640eb]
  cip/4.4-rt: [6f1117c4227fec8d321531df8cd72de9b6e640eb]
  cip/4.4-st: [6f1117c4227fec8d321531df8cd72de9b6e640eb]
  cip/5.10: [e757ff4bbc893bc030c2d10143091094da73b9ff]
  cip/5.10-rt: [e757ff4bbc893bc030c2d10143091094da73b9ff]
  debian/buster-security: ['version:debian/4.19.249-1']
  mainline: [b7c81f80246fac44077166f3e07103affe6db8ff]
  stable/4.14: [1269a6567274edecd04ee7fd7871aa4d0c937f2a]
  stable/4.19: [34380b5647f13fecb458fea9a3eb3d8b3a454709]
  stable/4.9: [2a08a260d2294b2ecd4190cceaaf12ae81f3cb9f]
  stable/5.10: [e757ff4bbc893bc030c2d10143091094da73b9ff]
  stable/5.15: [e259ba5c08d3791ab269b7775f1de5b36b06388c]
  stable/5.4: [34b9b91829111a7e44b593c790a22680c89cd402]
  ubuntu/bionic: [ede6ce0f4a7161da687c6359d0c9bbfdcec6f4ac]
  ubuntu/focal: [ce0eb104dcd53877260149430a9008f37ca3468a]
