description: 'nvme-tcp: fix possible use-after-free in transport error_recovery work'
references:
- https://www.cve.org/CVERecord?id=CVE-2022-48789
- https://git.kernel.org/stable/c/61a26ffd5ad3ece456d74c4c79f7b5e3f440a141
- https://git.kernel.org/stable/c/e192184cf8bce8dd55d619f5611a2eaba996fa05
- https://git.kernel.org/stable/c/5e42fca37ccc76f39f73732661bd47254cad5982
- https://git.kernel.org/stable/c/bb0d8fb35c4ff00a503c2c4dca4cce8d102a21c4
- https://git.kernel.org/stable/c/ff9fc7ebf5c06de1ef72a69f9b1ab40af8b07f9e
- https://lore.kernel.org/linux-cve-announce/2024071640-CVE-2022-48789-a066@gregkh/
- https://git.kernel.org/linus/ff9fc7ebf5c06de1ef72a69f9b1ab40af8b07f9e
comments:
  cip/cip-kernel-sec: There is no mention of the commit that introduced the bug in
    the CVE announcement.Fixed in v5.17-rc3.
  debian/carnil: First introducing commit could not be determined.
fixed-by:
  cip/5.10: [e192184cf8bce8dd55d619f5611a2eaba996fa05]
  cip/5.10-rt: [e192184cf8bce8dd55d619f5611a2eaba996fa05]
  mainline: [ff9fc7ebf5c06de1ef72a69f9b1ab40af8b07f9e]
  stable/5.10: [e192184cf8bce8dd55d619f5611a2eaba996fa05]
  stable/5.15: [5e42fca37ccc76f39f73732661bd47254cad5982]
  stable/5.4: [61a26ffd5ad3ece456d74c4c79f7b5e3f440a141]
  ubuntu/focal: [ec3ed211a6a810cd5fa20e84629a65c342ea16e0]
ignore:
  cip/4.19: Affected file is not present.
  cip/4.19-rt: Affected file is not present.
  cip/4.4: Affected file is not present.
  cip/4.4-rt: Affected file is not present.
  cip/4.4-st: Affected file is not present.
  stable/4.19: Affected file is not present.
