description: 'nvme-rdma: fix possible use-after-free in transport error_recovery work'
references:
- https://www.cve.org/CVERecord?id=CVE-2022-48788
- https://git.kernel.org/stable/c/5593f72d1922403c11749532e3a0aa4cf61414e9
- https://git.kernel.org/stable/c/d411b2a5da68b8a130c23097014434ac140a2ace
- https://git.kernel.org/stable/c/324f5bdc52ecb6a6dadb31a62823ef8c709d1439
- https://git.kernel.org/stable/c/646952b2210f19e584d2bf9eb5d092abdca2fcc1
- https://git.kernel.org/stable/c/ea86027ac467a055849c4945906f799e7f65ab99
- https://git.kernel.org/stable/c/b6bb1722f34bbdbabed27acdceaf585d300c5fd2
- https://lore.kernel.org/linux-cve-announce/2024071640-CVE-2022-48788-be08@gregkh/
comments:
  cip/cip-kernel-sec: There is no mention of the commit that introduced the bug in
    the CVE announcement.Fixed in v5.17-rc3.
  debian/carnil: First introducing commit could not be determined.
fixed-by:
  cip/4.19: [5593f72d1922403c11749532e3a0aa4cf61414e9]
  cip/4.19-rt: [5593f72d1922403c11749532e3a0aa4cf61414e9]
  cip/5.10: [324f5bdc52ecb6a6dadb31a62823ef8c709d1439]
  cip/5.10-rt: [324f5bdc52ecb6a6dadb31a62823ef8c709d1439]
  mainline: [b6bb1722f34bbdbabed27acdceaf585d300c5fd2]
  stable/4.19: [5593f72d1922403c11749532e3a0aa4cf61414e9]
  stable/5.10: [324f5bdc52ecb6a6dadb31a62823ef8c709d1439]
  stable/5.15: [646952b2210f19e584d2bf9eb5d092abdca2fcc1]
  stable/5.4: [d411b2a5da68b8a130c23097014434ac140a2ace]
  ubuntu/focal: [2da7c14ae853003ebb016e59fd5971a7adbc5609]
ignore:
  cip/4.4: Affected file is not present.
  cip/4.4-rt: Affected file is not present.
  cip/4.4-st: Affected file is not present.
