description: 'iommu/vt-d: Fix potential lockup if qi_submit_sync called with 0 count'
references:
- https://www.cve.org/CVERecord?id=CVE-2024-49993
- https://git.kernel.org/stable/c/de9e7f68762585f7532de8a06de9485bf39dbd38
- https://git.kernel.org/stable/c/8840dc73ac9e1028291458ef1429ec3c2524ffec
- https://git.kernel.org/stable/c/e03f00aa4a6c0c49c17857a4048f586636abdc32
- https://git.kernel.org/stable/c/dfdbc5ba10fb792c9d6d12ba8cb6e465f97365ed
- https://git.kernel.org/stable/c/07e4e92f84b7d3018b7064ef8d8438aeb54a2ca5
- https://git.kernel.org/stable/c/92ba5b014d5435dd7a1ee02a2c7f2a0e8fe06c36
- https://git.kernel.org/stable/c/3cf74230c139f208b7fb313ae0054386eee31a81
- https://lore.kernel.org/linux-cve-announce/2024102138-CVE-2024-49993-5b57@gregkh/
- https://git.kernel.org/linus/3cf74230c139f208b7fb313ae0054386eee31a81
comments:
  cip/cip-kernel-sec: There is no mention of the commit that introduced the bug in
    the CVE announcement.Fixed in v6.12-rc1.
  cip/masami: |-
    It seems as if this bug was introduced by commit 8a1d82462 ("iommu/vt-d:
    Multiple descriptors per qi_submit_sync()") in 5.8-rc1.
  debian/carnil: First introducing commit could not be determined.
introduced-by:
  mainline: [8a1d824625402b3ef3c3e5965663354ff0394d86]
fixed-by:
  cip/6.1: [e03f00aa4a6c0c49c17857a4048f586636abdc32]
  mainline: [3cf74230c139f208b7fb313ae0054386eee31a81]
  stable/5.10: [de9e7f68762585f7532de8a06de9485bf39dbd38]
  stable/5.15: [8840dc73ac9e1028291458ef1429ec3c2524ffec]
  stable/6.1: [e03f00aa4a6c0c49c17857a4048f586636abdc32]
  stable/6.11: [92ba5b014d5435dd7a1ee02a2c7f2a0e8fe06c36]
  stable/6.6: [dfdbc5ba10fb792c9d6d12ba8cb6e465f97365ed]
