description: 'usb: dwc2: check return value after calling platform_get_resource()'
references:
- https://www.cve.org/CVERecord?id=CVE-2021-47409
- https://git.kernel.org/stable/c/4b7f4a0eb92bf37bea4cd838c7f83ea42823ca8b
- https://git.kernel.org/stable/c/a7182993dd8e09f96839ddc3ac54f9b37370d282
- https://git.kernel.org/stable/c/8b9c1c33e51d0959f2aec573dfbac0ffd3f5c0b7
- https://git.kernel.org/stable/c/2754fa3b73df7d0ae042f3ed6cfd9df9042f6262
- https://git.kernel.org/stable/c/337f00a0bc62d7cb7d10ec0b872c79009a1641df
- https://git.kernel.org/stable/c/856e6e8e0f9300befa87dde09edb578555c99a82
- https://lore.kernel.org/linux-cve-announce/2024052151-CVE-2021-47409-1856@gregkh/
- https://git.kernel.org/linus/856e6e8e0f9300befa87dde09edb578555c99a82
comments:
  cip/cip-kernel-sec: Introduced commit is not determined.Fixed in v5.15-rc3.
  cip/masami: 'It was introduced by commit 348becd ("usb: dwc2: fix "iomem 0x00000000"
    message") in 4.11-rc1.'
  debian/carnil: First introducing commit could not be determined.
introduced-by:
  mainline: [348becdcc3196addbe882e8a10451744e489e389]
fixed-by:
  cip/4.19: [a7182993dd8e09f96839ddc3ac54f9b37370d282]
  cip/4.19-rt: [a7182993dd8e09f96839ddc3ac54f9b37370d282]
  cip/5.10: [2754fa3b73df7d0ae042f3ed6cfd9df9042f6262]
  cip/5.10-rt: [2754fa3b73df7d0ae042f3ed6cfd9df9042f6262]
  debian/buster-security: ['version:debian/4.19.232-1']
  mainline: [856e6e8e0f9300befa87dde09edb578555c99a82]
  openela/4.14: [4b7f4a0eb92bf37bea4cd838c7f83ea42823ca8b]
  stable/4.14: [4b7f4a0eb92bf37bea4cd838c7f83ea42823ca8b]
  stable/4.19: [a7182993dd8e09f96839ddc3ac54f9b37370d282]
  stable/5.10: [2754fa3b73df7d0ae042f3ed6cfd9df9042f6262]
  stable/5.4: [8b9c1c33e51d0959f2aec573dfbac0ffd3f5c0b7]
  ubuntu/bionic: [b9035d3596cf2b3afdbc112332f0bfe61b26ddd1]
  ubuntu/focal: [2497e05c5aa9081c6144bd14b5c3301da1e3d605]
