description: 'io_uring: ensure task_work gets run as part of cancelations'
references:
- https://www.cve.org/CVERecord?id=CVE-2021-47504
- https://git.kernel.org/stable/c/8e12976c0c19ebc14b60046b1348c516a74c25a2
- https://git.kernel.org/stable/c/78a780602075d8b00c98070fa26e389b3b3efa72
- https://lore.kernel.org/linux-cve-announce/2024052451-CVE-2021-47504-2a5d@gregkh/
comments:
  cip/cip-kernel-sec: There is no mention of the commit that introduced the bug in
    the CVE announcement.Fixed in v5.16-rc5.
  cip/masami: io_uring was introduced in 5.1 so 4.x is not affected.
  debian/carnil: First introducing commit could not be determined.
fixed-by:
  mainline: [78a780602075d8b00c98070fa26e389b3b3efa72]
  stable/5.15: [8e12976c0c19ebc14b60046b1348c516a74c25a2]
ignore:
  cip/4.19: io_uring is not supported
  cip/4.19-rt: io_uring is not supported
  cip/4.4: io_uring is not supported
  cip/4.4-rt: io_uring is not supported
  cip/4.4-st: io_uring is not supported
  stable/4.19: io_uring is not supported
