description: 'watchdog: Fix possible use-after-free by calling del_timer_sync()'
references:
- https://www.cve.org/CVERecord?id=CVE-2021-47321
- https://git.kernel.org/stable/c/58606882ad8ec6c39e0f40344b922921ef94ab4d
- https://git.kernel.org/stable/c/ca96b8ea5e74956071154bdb456778cc3027e79f
- https://git.kernel.org/stable/c/8bec568d7518b1504a602ed5376bb322e4dbb270
- https://git.kernel.org/stable/c/ecd620e0fb1ff7f78fdb593379b2e6938c99707a
- https://git.kernel.org/stable/c/db222f1477ad5692cd454709b714949807e5d111
- https://git.kernel.org/stable/c/66ba9cf929b1c4fabf545bd4c18f6f64e23e46e4
- https://git.kernel.org/stable/c/4c05dac488a660fe2925c047ecb119e7afaaeb1e
- https://git.kernel.org/stable/c/1a053c4d716898a53c2e31c574a70ea0c37044a3
- https://git.kernel.org/stable/c/d0212f095ab56672f6f36aabc605bda205e1e0bf
- https://lore.kernel.org/linux-cve-announce/2024052132-CVE-2021-47321-1b9b@gregkh/
- https://git.kernel.org/linus/d0212f095ab56672f6f36aabc605bda205e1e0bf
comments:
  cip/cip-kernel-sec: There is no mention of the commit that introduced the bug in
    the CVE announcement.Fixed in v5.14-rc1.
  debian/carnil: First introducing commit could not be determined.
fixed-by:
  cip/4.19: [ecd620e0fb1ff7f78fdb593379b2e6938c99707a]
  cip/4.19-rt: [ecd620e0fb1ff7f78fdb593379b2e6938c99707a]
  cip/4.4: [58606882ad8ec6c39e0f40344b922921ef94ab4d]
  cip/4.4-rt: [58606882ad8ec6c39e0f40344b922921ef94ab4d]
  cip/4.4-st: [58606882ad8ec6c39e0f40344b922921ef94ab4d]
  cip/5.10: [66ba9cf929b1c4fabf545bd4c18f6f64e23e46e4]
  cip/5.10-rt: [66ba9cf929b1c4fabf545bd4c18f6f64e23e46e4]
  debian/buster-security: ['version:debian/4.19.208-1']
  mainline: [d0212f095ab56672f6f36aabc605bda205e1e0bf]
  stable/4.19: [ecd620e0fb1ff7f78fdb593379b2e6938c99707a]
  stable/4.4: [58606882ad8ec6c39e0f40344b922921ef94ab4d]
  stable/5.10: [66ba9cf929b1c4fabf545bd4c18f6f64e23e46e4]
  stable/5.4: [db222f1477ad5692cd454709b714949807e5d111]
  ubuntu/bionic: [52ef6e190c9e004ada4df2a71cd2153d279aeecc]
  ubuntu/focal: [d15681f8b73ba5a52735defc714f49dfce1eeab9]
